version: '3'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      CONNECTION_STRING: "host=db user=postgres password=password dbname=postgres port=5432 sslmode=disable"
      SECRET_KEY: "todo-app"
      REDIS_URL: "redis:6379"

  

  